In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("train.csv")

In [2]:
df = pd.read_csv("train.csv")
df
# retirer les colonnes PassengerId, Name, Ticket, Cabin
data = df.drop(columns=["PassengerId", "Name", "Ticket", "Cabin"])
data
# Transformer Sex et Embarked en Valeur numérique
data["Sex"] = data["Sex"].map({"male": 0, "female": 1})
data
data["Embarked"] = data["Embarked"].map({
    np.nan: 0, "S": 1, "C": 2, "Q": 3
})
data
# faire un df.dropna() pour ne garder que les valeur non nan
data.dropna(subset=["Age"], inplace=True)
data.count()

Survived    714
Pclass      714
Sex         714
Age         714
SibSp       714
Parch       714
Fare        714
Embarked    714
dtype: int64

In [3]:
data.head(10)

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          0       3    0  22.0      1      0   7.2500         1
1          1       1    1  38.0      1      0  71.2833         2
2          1       3    1  26.0      0      0   7.9250         1
3          1       1    1  35.0      1      0  53.1000         1
4          0       3    0  35.0      0      0   8.0500         1
6          0       1    0  54.0      0      0  51.8625         1
7          0       3    0   2.0      3      1  21.0750         1
8          1       3    1  27.0      0      2  11.1333         1
9          1       2    1  14.0      1      0  30.0708         2
10         1       3    1   4.0      1      1  16.7000         1

In [4]:
data[data["Survived"] == 0].loc[:10]

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500         1
4         0       3    0  35.0      0      0   8.0500         1
6         0       1    0  54.0      0      0  51.8625         1
7         0       3    0   2.0      3      1  21.0750         1

In [5]:
data[data["Survived"] == 0].iloc[:10]

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          0       3    0  22.0      1      0   7.2500         1
4          0       3    0  35.0      0      0   8.0500         1
6          0       1    0  54.0      0      0  51.8625         1
7          0       3    0   2.0      3      1  21.0750         1
12         0       3    0  20.0      0      0   8.0500         1
13         0       3    0  39.0      1      5  31.2750         1
14         0       3    1  14.0      0      0   7.8542         1
16         0       3    0   2.0      4      1  29.1250         3
18         0       3    1  31.0      1      0  18.0000         1
20         0       2    0  35.0      0      0  26.0000         1

In [46]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(data.drop(columns=["Survived"]))

data_train = data.iloc[:500]
data_test = data.iloc[501:]

In [7]:
# data.to_numpy()

In [47]:


Y_train = data_train["Survived"]
raw_X_train = data_train.drop(columns=["Survived"])
X_train = scaler.transform(raw_X_train)

Y_test = data_test["Survived"]
raw_X_test = data_test.drop(columns=["Survived"])
X_test = scaler.transform(raw_X_test)


In [9]:
from sklearn.svm import SVC

clf = SVC()

clf.fit(X_train, Y_train)

score = clf.score(X_test, Y_test)
score

0.6995305164319249

In [10]:
# len(Y_test[Y_test == 0]) / len(Y_test)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier()

clf.fit(X_train, Y_train)

score = clf.score(X_test, Y_test)
score

0.7323943661971831

In [12]:
clf.predict(X_test.iloc[:10])

array([0, 0, 1, 1, 0, 0, 1, 1, 1, 1], dtype=int64)

In [13]:
Y_test.iloc[:10]

634    0
635    1
636    0
637    0
638    0
640    0
641    1
642    0
644    1
645    1
Name: Survived, dtype: int64

In [48]:
from sklearn.neighbors import KNeighborsClassifier

score_list = []
for n in range(1, 30):
    clf = KNeighborsClassifier(n_neighbors=n)

    clf.fit(X_train, Y_train)

    score = clf.score(X_test, Y_test)
    score_list.append((n, score))

score_list

[(1, 0.7370892018779343),
 (2, 0.8356807511737089),
 (3, 0.7981220657276995),
 (4, 0.7981220657276995),
 (5, 0.7981220657276995),
 (6, 0.8075117370892019),
 (7, 0.8215962441314554),
 (8, 0.812206572769953),
 (9, 0.812206572769953),
 (10, 0.7934272300469484),
 (11, 0.8075117370892019),
 (12, 0.7887323943661971),
 (13, 0.7934272300469484),
 (14, 0.7887323943661971),
 (15, 0.7934272300469484),
 (16, 0.7981220657276995),
 (17, 0.784037558685446),
 (18, 0.7934272300469484),
 (19, 0.7887323943661971),
 (20, 0.7981220657276995),
 (21, 0.7934272300469484),
 (22, 0.7981220657276995),
 (23, 0.7981220657276995),
 (24, 0.7981220657276995),
 (25, 0.8075117370892019),
 (26, 0.7981220657276995),
 (27, 0.8075117370892019),
 (28, 0.7887323943661971),
 (29, 0.7887323943661971)]

In [49]:
import numpy as np

# help(np.random.randn)
X = np.arange(30)
Y = np.random.randn(30)
# scores = np.array()
score_array = np.array(list(zip(X,Y)))
# help(np.random.random)


score_array = np.array(score_list)

In [16]:
score_array

array([[ 1.        ,  0.67605634],
       [ 2.        ,  0.69014085],
       [ 3.        ,  0.70422535],
       [ 4.        ,  0.70422535],
       [ 5.        ,  0.73239437],
       [ 6.        ,  0.72300469],
       [ 7.        ,  0.75586854],
       [ 8.        ,  0.72300469],
       [ 9.        ,  0.71361502],
       [10.        ,  0.71361502],
       [11.        ,  0.73239437],
       [12.        ,  0.72300469],
       [13.        ,  0.74178404],
       [14.        ,  0.7370892 ],
       [15.        ,  0.75117371],
       [16.        ,  0.75586854],
       [17.        ,  0.74647887],
       [18.        ,  0.75117371],
       [19.        ,  0.73239437],
       [20.        ,  0.73239437],
       [21.        ,  0.73239437],
       [22.        ,  0.72769953],
       [23.        ,  0.72300469],
       [24.        ,  0.72769953],
       [25.        ,  0.72300469],
       [26.        ,  0.72769953],
       [27.        ,  0.7370892 ],
       [28.        ,  0.71830986],
       [29.        ,

In [17]:
score_array[0,1]

0.676056338028169

In [18]:
score_array.shape

(29, 2)

In [19]:
score_array[0,:] # selectionner la premiere ligne
score_array[:,0] # selectionner la premiere colonne


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.])

In [55]:
# import tkinter
%matplotlib qt

import matplotlib.pyplot as plt

plt.plot(score_array[:,0], score_array[:,1])
plt.show()
# plt.savefig("scores.png")

In [34]:
i = np.argmax(score_array[:,1])
score_array[i,0]

7.0

In [37]:
data.plot.scatter("Age", "Fare", alpha=0.5, c=data["Survived"], cmap="Set1")

In [58]:
clf = KNeighborsClassifier(n_neighbors=2)
clf.fit(X_train, Y_train)

Y_predicted = clf.predict(X_test)
plt.subplot(2,1,1)
plt.scatter(raw_X_test["Age"], raw_X_test["Fare"], alpha=0.5, c=Y_predicted, cmap="jet")

plt.subplot(2,1,2)
plt.scatter(raw_X_test["Age"], raw_X_test["Fare"], alpha=0.5, c=Y_test, cmap="jet")
plt.show()

In [41]:
# help(plt.subplot)

In [45]:
X_train

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         3    0  22.0      1      0   7.2500         1
1         1    1  38.0      1      0  71.2833         2
2         3    1  26.0      0      0   7.9250         1
3         1    1  35.0      1      0  53.1000         1
4         3    0  35.0      0      0   8.0500         1
..      ...  ...   ...    ...    ...      ...       ...
626       2    0  57.0      0      0  12.3500         3
627       1    1  21.0      0      0  77.9583         1
628       3    0  26.0      0      0   7.8958         1
630       1    0  80.0      0      0  30.0000         1
631       3    0  51.0      0      0   7.0542         1

[500 rows x 7 columns]