In [1]:
class Personne:
    def __init__(self):
        self.nom = "Johnson"
        self.prenom = "John"
        
        


In [4]:
une_personne = Personne() # crée une instance de la classe Personne

print(une_personne)
print(une_personne.nom)

Johnson


In [5]:
une_autre_personne = Personne() # crée une instance de la classe Personne

print(une_autre_personne)
print(une_autre_personne.nom)

Johnson


In [7]:
une_autre_personne.nom = "Lincoln"

print(une_autre_personne)
print(une_autre_personne.nom)
print(une_personne.nom)


Lincoln
Johnson


In [10]:
class Personne:
    def __init__(self, nom_param, prenom_param, ville="Londres"):
        self.nom = nom_param
        self.prenom = prenom_param
        self.ville = ville
        
une_personne = Personne("Lovelace", "Ada")
print(une_personne.nom)
print(une_personne.ville)

une_autre_personne = Personne("Turing", "Alan", "Paris")
print(une_autre_personne.nom)
print(une_autre_personne.ville)


Lovelace
Londres
Turing
Paris


In [11]:
class Personne:
    def __init__(self, nom_param, prenom_param, ville="Londres"):
        assert type(nom_param) == str
        self.nom = nom_param
        self.prenom = prenom_param
        self.ville = ville
        
    def dire_bonjour(self):
        print(f"Bonjour ! Je m'appelle {self.prenom} {self.nom}.")
        
une_personne = Personne("Lovelace", "Ada")
print(une_personne.nom)
print(une_personne.ville)

une_autre_personne = Personne("Turing", "Alan", "Paris")
print(une_autre_personne.nom)
print(une_autre_personne.ville)
une_autre_personne.dire_bonjour()

Lovelace
Londres
Turing
Paris
Bonjour ! Je m'appelle Alan Turing.


In [18]:
class Voiture:
    """
        attributs:
        - marque: str
        - position: np.array
        - vitesse: np.array = np.array([0,1])
        methodes:
        - avancer() fait avancer la voiture du vecteur vitesse
        - tourner() tourner le vecteur vitesse dans le sens horraire
    """
    

# Créer une voiture.
# Faites la avancer.
# Faites la tourner
# Faites la avancer.

import numpy as np

mat = np.array([[1,4],[2,3]])
print(mat)
mat[0,1]



[[1 4]
 [2 3]]


4

In [23]:
une_personne.__dict__

{'nom': 'Lovelace', 'prenom': 'Ada', 'ville': 'Londres'}

In [24]:
vitesse = np.array([0,1])

rot = np.array([[0, -1], [1, 0]])
vitesse = rot.dot(vitesse)
vitesse

array([-1,  0])

In [26]:
type(np.array([0,1])) == np.ndarray

True

In [44]:
import numpy as np

class Voiture:
    """
        attributs:
        - marque: str
        - position: np.array
        - vitesse: np.array = np.array([0,1])
        methodes:
        - avancer() fait avancer la voiture du vecteur vitesse
        - tourner() tourner le vecteur vitesse dans le sens horraire
    """
    def __init__(self, marque, position, vitesse_param=np.array([0,1])):
        assert type(position) == np.ndarray and position.shape == (2,), \
            "position doit être un np.array de taille (2,)"
        assert type(vitesse_param) == np.ndarray and vitesse_param.shape == (2,), \
            "vitesse doit être un np.array de taille (2,)"
        self.marque = marque
        self.position = position
        self.vitesse = np.array(vitesse_param)
    
    def avancer(self):
        self.position += self.vitesse
        
    def tourner(self):
        self.vitesse = np.array([[0,-1],[1, 0]]).dot(self.vitesse)
    
    def __repr__(self):
        return f"Voiture : {self.marque}. Position : {self.position}"
    
    def __del__(self):
        print("bonjour")
        
    def __lt__(self, other):
        return self.position[0] < other.position[0]

    def __eq__(self, other):
        return self.position[0] == other.position[0]


# Créer une voiture.
une_voit = Voiture("Maybach", np.array([0,1]))
print(une_voit)
# Faites la avancer.
une_voit.avancer()
print(une_voit)
# Faites la tourner
une_voit.tourner()
print(une_voit)
# Faites la avancer.
une_voit.avancer()
# Voiture.avancer(une_voit)
print(une_voit)


Voiture : Maybach. Position : [0 1]
Voiture : Maybach. Position : [0 2]
Voiture : Maybach. Position : [0 2]
Voiture : Maybach. Position : [-1  2]


In [45]:
une_voit2 = Voiture("Kangoo", np.array([1,0]))

une_voit < une_voit2

True

In [28]:
# np.array([0,1]).dot(np.array([[0,-1],[1, 0]]))

array([1, 0])

In [43]:
# del une_voit
une_voit = Voiture("Kangoo", np.array([1,0]))


bonjour


In [40]:
print(une_voit)

NameError: name 'une_voit' is not defined

In [67]:
# Créer une classe Personne avec nom, prenom age
# Le print doit afficher le prenom
# il doit y avoir une relation d'ordre sur les ages
# faite une liste de personnes
# trier cette liste avec ma_iste.sort() et afficher le résultat
from random import randint


class Personne:
    def __init__(self, prenom, nom, age):
        self.prenom = prenom
        self.nom = nom
        self.age = age
        
    def __repr__(self):
        return f"{self.prenom} - {self.age} ans"
    
    def __lt__(self, other):
        return self.age < other.age
    
    def __eq__(self, other):
        return self.age == other.age
    

liste_personnes = [
    Personne(f"Martin{i}", f"Terrier{i}", randint(20, 50)) 
    for i in range(10)
]


In [68]:
liste_personnes

[Martin0 - 32 ans,
 Martin1 - 27 ans,
 Martin2 - 28 ans,
 Martin3 - 38 ans,
 Martin4 - 42 ans,
 Martin5 - 31 ans,
 Martin6 - 23 ans,
 Martin7 - 30 ans,
 Martin8 - 25 ans,
 Martin9 - 36 ans]

In [69]:
[p.age for p in liste_personnes]

[32, 27, 28, 38, 42, 31, 23, 30, 25, 36]

In [70]:
# liste_personnes.sort()
liste_personnes = sorted(liste_personnes)
liste_personnes

[Martin6 - 23 ans,
 Martin8 - 25 ans,
 Martin1 - 27 ans,
 Martin2 - 28 ans,
 Martin7 - 30 ans,
 Martin5 - 31 ans,
 Martin0 - 32 ans,
 Martin9 - 36 ans,
 Martin3 - 38 ans,
 Martin4 - 42 ans]

In [71]:
[p.age for p in liste_personnes]

[23, 25, 27, 28, 30, 31, 32, 36, 38, 42]

In [80]:
class Client(Personne):
    def __init__(self, nom, prenom, age, solde):
        Personne.__init__(self, nom, prenom, age)
        self.__solde = solde
        
    def __saluer(self):
        print("Bonjour")
        
    def solde(self):
        self.__saluer()
        return self.__solde
        
client1 = Client("Lecleach", "Arnaud", 42, 15000)
client2 = Client("Martin", "Gaultier", 38, 200000)

# client1.__solde
client1.solde()
# client1.__saluer()

Bonjour


15000

In [74]:
print(client1)
client1 > client2

Lecleach - 42 ans


True